### ISSUE TITLE
admin only

### ISSUE THREAD

**Issue by divians** [Sighmir/vrp_id_display#2] opened 2017-10-09 08:40 UTC
if ((distance < config.range)) then
                    if not config.admin_only or player[psource].admin then
                        if NetworkIsPlayerTalking(id) and config.speaker then DrawText3D(x2, y2, z2+1, config.lang[config.lang.default].talking.." | "..player[source].name.." | "..player[source].user_id)
                        else DrawText3D(x2, y2, z2+1, player[source].name.." | "..player[source].user_id) end
                    end

    -- Show names only for admins
    admin_only = true,

maybe add?

**Comment by Sighmir** [comment] 2017-10-09 08:50
Duplicate of #1

**Closed by Sighmir** 2017-10-09 08:50 UTC
